apiVersion: v1
kind: Secret
metadata:
  name: hospital-api-secrets
  namespace: hospital-api
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://hospitaladmin:Hospital123@cluster1.bhy6no3.mongodb.net/hospital-db?retryWrites=true&w=majority"
  JWT_SECRET: "hospital-super-secret-jwt-key-change-in-production-2024"